import {
  Hospital, Bed, Patient, Ambulance, AlertItem, AnalyticsSummary
} from '../types';

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: 1,
    name: "CityCare Central Hospital",
    branch_name: "Downtown Campus",
    code: "CCC-01",
    address: "100 Medical Center Blvd, Downtown",
    lat: 40.7128,
    lng: -74.0060,
    contact_phone: "+1-555-0101",
    emergency_status: "NORMAL",
    total_beds: 120,
    occupied_beds: 78,
    available_beds: 42,
    reserved_beds: 8,
    cleaning_beds: 4,
    icu_capacity: 30,
    ward_capacity: 70,
    er_capacity: 20,
    ventilators_total: 20,
    ventilators_available: 6,
    ecmo_available: true,
    trauma_level: "Level 1 Comprehensive",
    occupied_icu_beds: 22,
    available_icu_beds: 8,
    overall_occupancy_rate: 65.0,
    icu_occupancy_rate: 73.3,
    doctors_on_duty: 18,
    nurses_on_duty: 42,
    active_alerts_count: 2,
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    name: "MetroCare West Pavilion",
    branch_name: "Riverside Center",
    code: "MCW-02",
    address: "450 Westside Highway, Riverside",
    lat: 40.7306,
    lng: -74.0120,
    contact_phone: "+1-555-0102",
    emergency_status: "NORMAL",
    total_beds: 95,
    occupied_beds: 52,
    available_beds: 43,
    reserved_beds: 4,
    cleaning_beds: 2,
    icu_capacity: 24,
    ward_capacity: 55,
    er_capacity: 16,
    ventilators_total: 16,
    ventilators_available: 8,
    ecmo_available: false,
    trauma_level: "Level 2 Regional",
    occupied_icu_beds: 13,
    available_icu_beds: 11,
    overall_occupancy_rate: 54.7,
    icu_occupancy_rate: 54.2,
    doctors_on_duty: 12,
    nurses_on_duty: 28,
    active_alerts_count: 0,
    created_at: new Date().toISOString()
  },
  {
    id: 3,
    name: "Sunrise Memorial Medical Center",
    branch_name: "East Medical District",
    code: "SMM-03",
    address: "780 Sunrise Parkway, East District",
    lat: 40.7282,
    lng: -73.9840,
    contact_phone: "+1-555-0103",
    emergency_status: "SURGE",
    total_beds: 110,
    occupied_beds: 98,
    available_beds: 12,
    reserved_beds: 6,
    cleaning_beds: 4,
    icu_capacity: 28,
    ward_capacity: 65,
    er_capacity: 17,
    ventilators_total: 18,
    ventilators_available: 3,
    ecmo_available: true,
    trauma_level: "Level 1 Comprehensive",
    occupied_icu_beds: 26,
    available_icu_beds: 2,
    overall_occupancy_rate: 89.1,
    icu_occupancy_rate: 92.9,
    doctors_on_duty: 15,
    nurses_on_duty: 35,
    active_alerts_count: 4,
    created_at: new Date().toISOString()
  }
];

export const MOCK_BEDS: Bed[] = [
  { id: 1, code: 'CCC01-ICU-01', bed_type: 'ICU', status: 'OCCUPIED', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 1, department_name: 'Intensive Care Unit', patient_id: 1, patient_name: 'Arthur Pendelton', equipment: JSON.stringify(['Ventilator', 'Oxygen', 'Cardiac Monitor']) },
  { id: 2, code: 'CCC01-ICU-02', bed_type: 'ICU', status: 'OCCUPIED', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 1, department_name: 'Intensive Care Unit', patient_id: 2, patient_name: 'Eleanor Vance', equipment: JSON.stringify(['Ventilator', 'Oxygen', 'Cardiac Monitor']) },
  { id: 3, code: 'CCC01-ICU-03', bed_type: 'ICU', status: 'AVAILABLE', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 1, department_name: 'Intensive Care Unit', equipment: JSON.stringify(['Ventilator', 'Oxygen', 'Cardiac Monitor']) },
  { id: 4, code: 'CCC01-ICU-04', bed_type: 'ICU', status: 'AVAILABLE', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 1, department_name: 'Intensive Care Unit', equipment: JSON.stringify(['Ventilator', 'Oxygen', 'Cardiac Monitor']) },
  { id: 5, code: 'CCC01-ICU-05', bed_type: 'ICU', status: 'RESERVED', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 1, department_name: 'Intensive Care Unit', equipment: JSON.stringify(['Ventilator', 'Oxygen', 'Cardiac Monitor']) },
  { id: 6, code: 'CCC01-ICU-06', bed_type: 'ICU', status: 'CLEANING', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 1, department_name: 'Intensive Care Unit', equipment: JSON.stringify(['Ventilator', 'Oxygen', 'Cardiac Monitor']) },
  { id: 7, code: 'CCC01-WRD-01', bed_type: 'GENERAL', status: 'OCCUPIED', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 2, department_name: 'General Ward', patient_id: 3, patient_name: 'Carlos Mendez', equipment: JSON.stringify(['Oxygen']) },
  { id: 8, code: 'CCC01-WRD-02', bed_type: 'GENERAL', status: 'AVAILABLE', hospital_id: 1, hospital_name: 'CityCare Central', department_id: 2, department_name: 'General Ward', equipment: JSON.stringify(['Oxygen']) }
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 1,
    mrn: 'MRN-10029',
    full_name: 'Arthur Pendelton',
    age: 64,
    gender: 'Male',
    blood_group: 'O+',
    admission_date: new Date().toISOString(),
    status: 'CRITICAL',
    triage_priority: 'RED',
    diagnosis: 'Acute Anterior STEMI with Cardiogenic Shock',
    hospital_id: 1,
    hospital_name: 'CityCare Central Hospital',
    department_id: 1,
    department_name: 'Intensive Care Unit',
    assigned_bed_id: 1,
    bed_code: 'CCC01-ICU-01',
    assigned_doctor_name: 'Dr. Sarah Jenkins',
    assigned_nurse_name: 'Nurse Elena Rostova',
    ai_risk_score: 88,
    ai_risk_level: 'CRITICAL',
    news2_score: 8,
    latest_vitals: {
      id: 101,
      patient_id: 1,
      heart_rate: 114,
      systolic_bp: 88,
      diastolic_bp: 56,
      spo2: 91,
      respiratory_rate: 24,
      temperature: 37.8,
      pain_score: 8,
      consciousness: 'ALERT',
      news2_score: 8,
      timestamp: new Date().toISOString(),
      recorded_by_nurse_name: 'Nurse Elena Rostova'
    }
  },
  {
    id: 2,
    mrn: 'MRN-10034',
    full_name: 'Eleanor Vance',
    age: 58,
    gender: 'Female',
    blood_group: 'A+',
    admission_date: new Date().toISOString(),
    status: 'HIGH_RISK',
    triage_priority: 'RED',
    diagnosis: 'Severe Sepsis secondary to Community Acquired Pneumonia',
    hospital_id: 1,
    hospital_name: 'CityCare Central Hospital',
    department_id: 1,
    department_name: 'Intensive Care Unit',
    assigned_bed_id: 2,
    bed_code: 'CCC01-ICU-02',
    assigned_doctor_name: 'Dr. Sarah Jenkins',
    assigned_nurse_name: 'Nurse Elena Rostova',
    ai_risk_score: 72,
    ai_risk_level: 'HIGH',
    news2_score: 6,
    latest_vitals: {
      id: 102,
      patient_id: 2,
      heart_rate: 102,
      systolic_bp: 96,
      diastolic_bp: 62,
      spo2: 93,
      respiratory_rate: 22,
      temperature: 38.6,
      pain_score: 5,
      consciousness: 'ALERT',
      news2_score: 6,
      timestamp: new Date().toISOString(),
      recorded_by_nurse_name: 'Nurse Elena Rostova'
    }
  },
  {
    id: 3,
    mrn: 'MRN-10041',
    full_name: 'Carlos Mendez',
    age: 42,
    gender: 'Male',
    blood_group: 'B+',
    admission_date: new Date().toISOString(),
    status: 'STABLE',
    triage_priority: 'YELLOW',
    diagnosis: 'Post-Op Day 2 Laparoscopic Appendectomy',
    hospital_id: 1,
    hospital_name: 'CityCare Central Hospital',
    department_id: 2,
    department_name: 'General Ward',
    assigned_bed_id: 7,
    bed_code: 'CCC01-WRD-01',
    assigned_doctor_name: 'Dr. David Cho',
    assigned_nurse_name: 'Nurse Jack Collins',
    ai_risk_score: 22,
    ai_risk_level: 'LOW',
    news2_score: 0,
    latest_vitals: {
      id: 103,
      patient_id: 3,
      heart_rate: 74,
      systolic_bp: 122,
      diastolic_bp: 78,
      spo2: 98,
      respiratory_rate: 16,
      temperature: 36.8,
      pain_score: 2,
      consciousness: 'ALERT',
      news2_score: 0,
      timestamp: new Date().toISOString(),
      recorded_by_nurse_name: 'Nurse Jack Collins'
    }
  }
];

export const MOCK_AMBULANCES: Ambulance[] = [
  {
    id: 1,
    code: 'AMB-101',
    vehicle_number: 'EMS-NY-4192',
    driver_name: 'Marcus Brody',
    paramedic_name: 'Jenna Morales',
    phone: '+1-555-0911',
    status: 'EN_ROUTE',
    lat: 40.7200,
    lng: -74.0010,
    destination_hospital_id: 1,
    destination_hospital_name: 'CityCare Central Hospital',
    current_patient_name: 'David Keller (Trauma MVA)',
    assigned_bed_code: 'CCC01-ICU-05',
    assigned_doctor_name: 'Dr. Sarah Jenkins',
    eta_minutes: 4,
    speed_kmh: 52,
    equipment: JSON.stringify(['Defibrillator', 'Transport Ventilator', 'Lucas CPR', 'Telemetry ECG'])
  },
  {
    id: 2,
    code: 'AMB-102',
    vehicle_number: 'EMS-NY-5231',
    driver_name: 'Robert Torres',
    paramedic_name: 'Lisa Chang',
    phone: '+1-555-0912',
    status: 'TRANSPORTING',
    lat: 40.7350,
    lng: -74.0080,
    destination_hospital_id: 2,
    destination_hospital_name: 'MetroCare West Pavilion',
    current_patient_name: 'Grace Hopper (Stroke Triage)',
    assigned_bed_code: 'MCW02-ICU-03',
    assigned_doctor_name: 'Dr. Michael Chen',
    eta_minutes: 7,
    speed_kmh: 48,
    equipment: JSON.stringify(['Defibrillator', 'Oxygen Port', 'Stroke Triage Kit'])
  },
  {
    id: 3,
    code: 'AMB-103',
    vehicle_number: 'EMS-NY-6110',
    driver_name: 'Ahmed Hassan',
    paramedic_name: 'Samantha Ray',
    phone: '+1-555-0913',
    status: 'AVAILABLE',
    lat: 40.7128,
    lng: -74.0060,
    destination_hospital_id: 1,
    destination_hospital_name: 'CityCare Central Hospital',
    eta_minutes: 0,
    speed_kmh: 0,
    equipment: JSON.stringify(['Defibrillator', 'Oxygen Kit'])
  }
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: 1,
    title: 'High Acuity Deterioration - NEWS2 Score 8',
    message: 'Patient Arthur Pendelton (Bed CCC01-ICU-01) exhibits acute desaturation (SpO2 91%) and tachycardia (HR 114 bpm).',
    severity: 'CRITICAL',
    alert_type: 'VITALS_DETERIORATION',
    target_role: 'ALL',
    hospital_id: 1,
    patient_id: 1,
    is_read: false,
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    title: 'Emergency Transport En Route - ETA 4 Mins',
    message: 'Ambulance AMB-101 inbound with critical trauma patient. Pre-allocated Bed CCC01-ICU-05.',
    severity: 'HIGH',
    alert_type: 'AMBULANCE_DISPATCH',
    target_role: 'NURSE',
    hospital_id: 1,
    is_read: false,
    created_at: new Date().toISOString()
  }
];

export const MOCK_ANALYTICS: AnalyticsSummary = {
  total_hospitals: 12,
  total_beds: 516,
  total_occupied_beds: 342,
  total_available_beds: 174,
  total_icu_beds: 156,
  available_icu_beds: 42,
  network_overall_occupancy_rate: 66.3,
  network_icu_occupancy_rate: 73.1,
  active_ambulances: 9,
  critical_patients: 14,
  high_risk_patients: 22,
  active_alerts: 5,
  avg_ambulance_response_mins: 8.2,
  total_admissions_today: 34,
  total_discharges_today: 18
};
